import {
  LayoutDashboard,
  Users,
  Sliders,
  Sparkles,
  Target,
  ShoppingBag,
} from 'lucide-react';
import type { NavItemConfig } from './types';

export const NAV_ITEMS: NavItemConfig[] = [
  {
    id: 'overview',
    label: 'Executive Overview',
    shortLabel: 'Overview',
    description: 'Macro portfolio GMV, revenue at risk & RFM cohorts',
    breadcrumbs: ['Mercury Intelligence', 'Executive Command', 'Overview'],
    badgeText: 'Live GMV',
    badgeType: 'emerald',
    icon: LayoutDashboard,
  },
  {
    id: 'customers',
    label: 'Customers & 360',
    shortLabel: 'Customers',
    description: 'Directory, RFM quintile radar & churn scoring',
    breadcrumbs: ['Customer Intelligence', 'Directory & 360 Profile'],
    badgeText: '17.6k At Risk',
    badgeType: 'crimson',
    icon: Users,
  },
  {
    id: 'churn-simulator',
    label: 'Churn Simulator',
    shortLabel: 'Simulator',
    description: 'Real-time counterfactual operational what-if dials',
    breadcrumbs: ['Machine Learning', 'Counterfactual Churn Lab'],
    badgeText: 'AUC 0.87',
    badgeType: 'violet',
    icon: Sliders,
  },
  {
    id: 'retention-planner',
    label: 'Retention Planner',
    shortLabel: 'Retention',
    description: 'Prescriptive playbooks & Knapsack budget allocation',
    breadcrumbs: ['Retention Economics', 'Playbooks & Knapsack Budget'],
    badgeText: '6 Playbooks',
    badgeType: 'cyan',
    icon: Sparkles,
  },
  {
    id: 'marketing-funnel',
    label: 'Marketing Funnel',
    shortLabel: 'Marketing',
    description: 'B2B MQL conversion, channel attribution & sales cycle',
    breadcrumbs: ['Marketplace B2B', 'Funnel & Sales Velocity'],
    badgeText: '10.5% Conv',
    badgeType: 'amber',
    icon: Target,
  },
  {
    id: 'catalog-intelligence',
    label: 'Catalog & Sellers',
    shortLabel: 'Catalog',
    description: 'Product categories, rating velocity & seller delivery delay',
    breadcrumbs: ['Marketplace Operations', 'Products & Sellers'],
    badgeText: '32.9k SKUs',
    badgeType: 'neutral',
    icon: ShoppingBag,
  },
];
